#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#@ def namespace_name(component):
name: #@ "{}-{}".format(component, data.values.build_id)
namespace: #@ data.values.namespace
#@ end

#@ def metadata(component):
_: #@ template.replace(namespace_name(component))
annotations:
  kapp.k14s.io/disable-original: ""
labels:
  supplychain.cc.build/part-of: catalog.cartographer.tanzu.vmware.com
  supplychain.cc.build/component: #@ component
  supplychain.cc.build/git-commit: #@ data.values.repo.commit
#@ end

#@ def git():
git:
  url: #@ data.values.repo.url
  ref:
    branch: #@ data.values.repo.branch
    commit: #@ data.values.repo.commit
#@ end

#@ def image(component):
#@   return "{}/{}/{}:{}".format(data.values.registry.host, data.values.registry.path, component, data.values.version)
#@ end

---
apiVersion: supplychain.cc.build/v1alpha2
kind: Request
metadata: #@ metadata("woke-image")
spec:
  artifacts:
    images:
      - name: #@ image("woke-image")
  buildType: kaniko
  buildConfig:
    kanikoBuildConfig:
      subPath: images/woke
      dockerfile: Dockerfile
      extraArgs: []
  source: #@ git()
  isOfficial: #@ data.values.official