---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: woke-scan-cluster-role
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: woke-scan
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: woke-scan
    app.kubernetes.io/part-of: woke-scan
    app.kubernetes.io/managed-by: kustomize
rules:
  - apiGroups:
      - kpack.io
    resources:
      - clusterbuilders
    verbs:
      - get
      - list
  - apiGroups:
      - kpack.io
    resources:
      - builds
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch