apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/instance: pull-secret
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: woke-scan
    app.kubernetes.io/part-of: woke-scan
    app.kubernetes.io/managed-by: kustomize
  name: pull-secret
  namespace: system
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K