apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: woke-scan
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: woke-scan
    app.kubernetes.io/part-of: woke-scan
    app.kubernetes.io/managed-by: kustomize
  name: woke-scan
  namespace: system
imagePullSecrets:
  - name: pull-secret
