---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: woke-scan
  namespace: tap-install
  annotations:
    ext.packaging.carvel.dev/fetch-0-secret-name: dev-registry-credentials
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: catalog.cartographer.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.1
