#@ load("@ytt:data", "data")
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: woke:latest
    path: images/woke
    docker:
      buildx:
        rawOptions: ["--platform", "linux/amd64", "--provenance=false"]
destinations:
  - image: woke:latest
    newImage: #@ data.values.build.registry_host + "/" + data.values.build.registry_project + "/woke"
