---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/source_insight_tooling/osspi-runner

inputs:
  - name: ci-repo
  - name: repo
params:
  REPO:
  API_KEY:
  OSM_ENVIRONMENT: beta
  OSSTP_LOAD_DRY_RUN:
  OSM_PACKAGE_GROUP_NAME:
  OSM_PACKAGE_GROUP_VERSION:
  USERNAME:
  PRODUCT:
  VERSION:
run:
  path: ci-repo/ci/tasks/osspi/run-single-package-for-repo.sh
